bin/cli.js
package.json
src/bundle.js
src/rollup-config.js
test/jsx/package.json
test/jsx/test.jsx

* support jsx option
* parsing jsx with buble
* downgrade rollup to 1.19 to fix acorn version conflicts
reference: https://github.com/acornjs/acorn-jsx/issues/103

feature: support jsx

---

README.md
src/cli.ts
test/cli.test.js

* `--shebang` to `-b, --bin` for shorter typing

enhance: rename shebang arg to bin

---

README.md
package.json
src/cli.ts
src/rollup-config.ts
test/cli.test.js
tsconfig.json
yarn.lock

Resolves #24 
* drop `-b` arg, user need to manually add shebang header
* use preseve-shebang plugin

feature: preserve shebang

---

env.d.ts
package.json
src/rollup-config.ts
tsconfig.json

* declare for untyped modules
* use `ts-node` instead of `node -t ts-node/register` to be able to search declarated types

types: support typing for shebang plugin

---

src/rollup-config.ts
src/types.ts
src/utils.ts
test/integration.test.js
test/integration/pkg-exports/index.js
test/integration/pkg-exports/package.json
test/unit/ts-interop/tsconfig.json

Support `exports` field in package.json
* string: `"exports:" "./dist/index.js"`
* object: `"exports": { "require": "./dist/index.cjs", "import": "./dist/index.mjs" }`

feat: exports field

---

src/rollup-config.ts
test/cli.test.js

Fixes #72
Rollup default value of `output.exports` `"auto"` might somehow output `module.exports = defautExport` which is not expected. Force to named exports in rollup config atm.
If you're using cjs and you have `export default` in source code, you need to explicitly use `mod.default` to access the default export in cjs
```js
const modDefaultExport = require('cjs-module').default
```

stick to named exports

---

package.json
src/bundle.ts
src/cli.ts
src/rollup-config.ts
test/__snapshots__/compile.test.js.snap
yarn.lock

Resolves #75 
* better error logging for watch mode
* bump related rollup deps for some bug fixes (such as do not abort when error in watch, support for `node:`)
* disable `noEmitOnError` for watch mode

Do not abort for watch mode when errors

---

package.json
test/__snapshots__/compile.test.js.snap
test/unit/shebang/input.js
yarn.lock

Fixes #77 
The commonjs plugin v22 adding `?commonjs-entry` query to the chunk, which will break the shebang preserve plugin. `facadeModuleId` will be mismatched. downgrade the commonjs to previous version

fix: shebang missing

---

.github/workflows/ci.yml

- Adds Node 16 & 18 to the matrix
- Updates:
- `actions/checkout@v2` -> `actions/checkout@v3`
- `actions/setup-node@v1` -> `actions/setup-node@v3`
- Enables reproducible dependencies via the `--frozen-lockfile` flag
- Caching of Yarn's global package cache
- Only pulls dependencies dependencies from the registry that aren't cached

ci: increase coverage and expand functionality

---

package.json
yarn.lock

I was running into this...
```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
.
└─┬ bunchee
└─┬ @rollup/plugin-json
└── ✕ unmet peer rollup@^1.20.0: found 2.74.1 in bunchee
```
...when installing dependencies and, upon inspection, saw that `@babel/core` was encountering similar issues.
This PR adds `@babel/core` and bumps `@rollup/plugin-json`.
I can see that you're working on integrating SWC, so the `@babel/core` addition is likely somewhat moot, but I changed both to ensure that everything's working in the meantime.
Thanks!

fix(deps): fix unmet peer dependency issues

---

package.json
test/compile.test.js
test/unit/es-advance/output-es-advance.snapshot.js
test/unit/es-basic/output-es-basic.snapshot.js
test/unit/jsx/output-jsx.snapshot.js
test/unit/module/output-module.snapshot.js
test/unit/shebang/output-shebang.snapshot.js
test/unit/sub-folder-import/output-sub-folder-import.snapshot.js
test/unit/ts-basic/output-ts-basic.snapshot.js
test/unit/ts-interop/output-ts-interop.snapshot.js
test/unit/tsx/output-tsx.snapshot.js

Generate `test/<case>/output-<case>.snapshot.js` for compilation result for unit testing. Replace existing jest snapshots. In this way the compile result can be easily separated case by case, much easier to diff and manage the changes

test: custom snapshot

---

src/rollup-config.ts

js files will be minified by swc when it's enabled, so we don't apply the terser onto them but only for typescript for now.

Fix: only apply terser for ts

---

src/rollup-config.ts

When specifying the `minify` and `sourcemap` options simultaneously via the CLI, the following message appears in the terminal:
```sh
Sourcemap is likely to be incorrect: a plugin (swc) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (swc) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```
The Rollup documentation details [why this warning appears](https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect):
> You'll see this warning if you generate a sourcemap with your bundle (sourcemap: true or sourcemap: 'inline') but you're using one or more plugins that transformed …

Ensure sourcemap is generated by SWC minify

---

src/rollup-config.ts
test/cli.test.js

Ignore the warnings are from bundled assets or from external dependencies
* Ignore `THIS_IS_UNDEFINED` warning: `The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten`, the structure of `THIS_IS_UNDEFINED` warning is not tracible to the original file. Or it can be pretty unrelated.
* Ignore `CIRCULAR_DEPENDENCY` warning if it's from 3rd party package in node_modules

enhance: ignore this undefined and circular dep warnings

---

src/rollup-config.ts

The default output format is esm when there's no format speicifier. In the format extraction process from package.json, it should align with the global default format instead of using cjs when there's no exports field detected.

Fix: align default output format

---

cli.ts
src/bundle.ts

Resolves #104
Filter out the rollup plugin object error, only log the formatted frame and throw the error to top-level with existing trace

Improve error logging

---

README.md
cli.ts
package.json
src/rollup-config.ts
src/types.ts
src/utils.ts

`target` will be used as the compilation target (such as es5 / es2020) in the future, and we rename it to `runtime`, but still represent the similar thing like "target environment" in webpack

BREAKING: Rename target to runtime

---

README.md
cli.ts
src/bundle.ts
src/rollup-config.ts
src/types.ts
src/utils.ts
test/cli.test.js
test/fixtures/es2020.js

Resolves #45 
With this change you can speicify `--target` with any swc supported es target (like `es5 | es3 | es2018 | es2020`) to speicify your js bundle compiled target

Support ES features compile target

---

package.json
src/rollup-config.ts
test/cli.test.js
test/compile.test.js
test/unit/jsx-preserve/__snapshot__/jsx-preserve.js.snapshot
test/unit/jsx-preserve/__snapshot__/jsx-preserve.min.js.snapshot
test/unit/jsx-preserve/input.tsx
test/unit/jsx-preserve/tsconfig.json
test/unit/jsx-react-automatic/__snapshot__/jsx-react-automatic.js.snapshot
test/unit/jsx-react-automatic/__snapshot__/jsx-react-automatic.min.js.snapshot
test/unit/jsx-react-automatic/input.tsx
test/unit/jsx-react-automatic/package.json
test/unit/jsx-react-automatic/tsconfig.json
yarn.lock

Resolves #117 
Reading tsconfig if there's one from the working directory, and passdown the `compilerOptions.jsx` option value to typescript plugin to align the compilation result with what tsconfig specified.
Notice that we're using swc to compile the typescript now, so `"jsx": "preserve"` won't preserve the original jsx syntax but will still compile to js code. Here's the [thread about that feature on swc side](https://github.com/swc-project/swc/pull/5661).

Respect jsx setting in tsconfig

---

cli.ts
src/rollup-config.ts
src/utils.ts

If you're using typescript but without specifying a tsconfig.json, it might cause build error especially when the directory output aren't clear.
So if you're using typescript, `tsconfig.json` is always required to be created in your top level directory

Check existence of tsconfig.json

---

package.json
test/tsconfig.json
yarn.lock

update swc plugin and swc itself to latest minor version
x-ref: https://github.com/SukkaW/rollup-plugin-swc/releases/tag/0.6.0
x-ref: https://github.com/swc-project/swc/releases/tag/v1.3.0
cc @SukkaW

chore: bump deps

---

src/rollup-config.ts
test/cli.test.ts
test/fixtures/package/index.ts
test/fixtures/package/package.json
test/fixtures/package/tsconfig.json

typing path should be absolute path that resolved with `cwd` option

Fix type paths with cwd option

---

.gitignore
cli.ts
src/bundle.ts
src/rollup-config.ts
test/cli.test.ts
test/fixtures/single-entry/package.json
test/fixtures/single-entry/src/index.js
test/integration/single-entry/package.json

Fixes #171 
Use specified entry path as priority when single entry is detected, if there's no specified entry path, then use fallback logic to find the default entry
Also remove few unnecessary `as` casting in the codebase

Fix custom entry path is broken

---

.github/workflows/ci.yml
package.json

Since node 16 is entering maintanance and node 14 will end maintainance soon, change the required version to 16. 
Also this is to prepare for integration of `publint`

require node 16

---

README.md
cli.ts
package.json
src/rollup-config.ts
src/types.ts
test/cli.test.ts
test/fixtures/env-var-consumer/index.js
test/fixtures/modules/foo.js
test/tsconfig.json
test/typing.test.ts
tsconfig.json
yarn.lock

Support a new way to leverage `process.env` into your bundle
```
bunchee --env NODE_ENV,RUNTIME,DOMAIN
```
Resolves #167

Support inline env values

---

package.json
src/build-config.ts
src/bundle.ts
src/cli.ts
src/config.ts
src/exports.ts
src/typescript.ts
src/utils.ts
test/cli.test.ts
test/compile.test.ts
test/integration.test.ts
test/integration/ts-allow-js/package.json
test/integration/ts-allow-js/src/index.js
test/integration/ts-allow-js/tsconfig.json
test/testing-utils.ts
test/tsconfig.json

Detect if there's `tsconfig.json` then treat it as typescript project weather users enabled `allowJs` configuration. As you always need custom `tsconfig.json` for typescript files.
When users have allowJs, source js file should emit types as well like ts files
Resolves #193 
* Refactor the `cwd` passing, remove `config.rootDir` as we only need it consume it on top level of bundling process
* Extract more helpers for building config into `src/build-config.ts` to decouple the logic from `bundle.ts`
* Improve test suite, specify `distFile` explicitly and use more async operations

Detect ts project by tsconfig and emit types if presented

---

package.json
src/build-config.ts
src/bundle.ts
src/logging.ts
src/plugins/size-plugin.ts
src/types.ts
src/utils.ts
test/cli.test.ts
test/integration.test.ts
yarn.lock

Resolves #194 
Example
```
✓  Typed dist/client.d.ts      - 74 B
✓  Typed dist/index.d.ts       - 65 B
✓  Typed dist/lite.d.ts        - 70 B
✓  Typed dist/client.d.ts      - 74 B
✓  Built dist/index.js         - 110 B
✓  Built dist/lite.js          - 132 B
✓  Built dist/client/index.cjs - 138 B
✓  Built dist/client/index.mjs - 78 B
```

Output size of generated types and js assets

---

src/build-config.ts
src/exports.ts
test/integration.test.ts
test/integration/pkg-exports-default/index.js

* refactor the code: should generate esMark when available, now also checking `exports` field
* set interop to `'auto'`, always use interop for cjs
x-ref: https://github.com/vercel/swr/issues/2580

Fix applying interop

---

src/build-config.ts
src/bundle.ts
src/exports.ts
src/plugins/size-plugin.ts
src/types.ts
test/integration.test.ts
test/integration/multi-entries/package.json
test/integration/multi-entries/src/edge.server.ts
test/lib/exports.test.ts

* Parse recursively to get the exports path mapping
* support more fields (browser/node/default/edge-light/react-server/...)
resolves #203

Refactor parsing exports

---

src/exports.ts
test/lib-unit/exports.test.ts

For mixed case, `exports: { import, module, ... }` should be assigned to `exportPaths['.']`

Fix complex mixed exports detection

---

src/build-config.ts
src/bundle.ts
src/exports.ts
src/utils.ts
test/integration.test.ts
test/integration/multi-entries/package.json
test/integration/multi-entries/src/edge.server.ts
test/integration/multi-entries/src/server/index.edge-light.ts
test/integration/multi-entries/src/server/index.react-server.ts
test/integration/multi-entries/src/shared.edge-light.ts
test/integration/multi-entries/src/shared.ts

For special platform that potential could have different entry file such as `react-server`, `edge-light` or `react-native` as they could contain their own thing or could potentially have different exports.
So bunchee provides a new convention `index.[export-type].js` to override the special exports
For instance, you have `index.js` as entry file for `exports.import` and `exports.require`. But you wanna use a similar entry file which is slightly different that doesn't contain some exports for `exports.react-server` condition.
```js
"exports": {
"import": "./dist/index.mjs",
"react-server": "./dist/react-server.mjs",
}
```
For `index.js` you might export stuffs that both available for client and server
```js
// ./dist/index.mjs
export const name = 'name'
export function …
```

Conventional entry for special platform exports

---

env.d.ts
package.json
src/build-config.ts
src/plugins/directive-plugin.ts
test/unit/use-client/__snapshot__/use-client.js.snapshot
test/unit/use-client/__snapshot__/use-client.min.js.snapshot
test/unit/use-client/input.js
yarn.lock

If string directives like `"use xxx"` and `#! xxx` are detected, will remove it from the input and append them into the final chunk
Resolves #187

preserve directives

---

package.json
src/build-config.ts
yarn.lock

Extract the previous shebang and directives preserving plugin (added in #221) as an [3rd party dependency - rollup-swc-preserve-directives](https://www.npmjs.com/package/rollup-swc-preserve-directives) so that everyone needs to customize  rollup can leverage that to help preserve shebang or directives.

Use 3rd party rollup-swc-preserve-directives

---

src/exports.ts
test/lib-unit/exports.test.ts

Extends https://github.com/huozhi/bunchee/issues/231#issuecomment-1632841266
@huozhi Not sure if this is the way you've wanted. 😅

chore: prioritize exports.require over pkg.main

---

package.json
pnpm-lock.yaml
src/build-config.ts
test/unit/use-client/__snapshot__/use-client.js.snapshot

preserve-directive plugin v0.3.0 handles removing the directives from source code so we don't have to skip the warning any more

Update preserve directive dep

---

src/exports.ts

As we already normalized the `exports` info mation so that it's hard to determine if the `pathsMap['.']?.['require']` is from `package.main` or `exports` field, let's remove this for now and re-add it later properly with detecting if both exists and conflicts
Closes #238

Remove duplicated exports warning

---

README.md

`entries .` has an unexpected empty space.

docs: remove unexpected empty space before dot

---

src/build-config.ts
src/cli.ts
src/types.ts
test/cli.test.ts
test/fixtures/cjs-relative-imports/cjs-dep.cjs
test/fixtures/cjs-relative-imports/index.js
test/fixtures/cjs-relative-imports/js-dep.js

Closes #254 
* Fix `commonjs` plugin reoslving, should respect to `externals` dependency
* Fix `externals` passing down logic

Fix commonjs bundle

---

src/exports.ts
src/lib/wildcard.ts
src/utils.ts
test/integration.test.ts
test/integration/esm-pkg-cjs-main-field/package.json
test/integration/esm-pkg-cjs-main-field/src/index.cjs

Shouldn't configure a cjs file in `main` filed when package is marked as esm module. Give an error for this case
Closes #268

Error on invalid main field export

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml

x-ref: https://github.com/huozhi/bunchee/actions/runs/6598833270/job/17927209278
error trace
```
console.error
(node:2886) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///home/runner/work/bunchee/bunchee/node_modules/.pnpm/tsx%403.12.6/node_modules/tsx/dist/loader.js", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
```
Old version of tsx doesn't support node 20 loader, upgrade tsx and add nodejs 20 back to CI

ci: upgrade tsx and add node 20 back

---

src/build-config.ts
test/integration.test.ts
test/integration/ts-incremental/package.json
test/integration/ts-incremental/src/index.ts
test/integration/ts-incremental/tsconfig.json

Fixes #280 
`convertCompilerOptions` need to be awaited and access the returned options from it.
For `incremental` option, since it's bounded with the `tsBuildInfoFile` option, we delete both of them if increamental is not enabled, for dts plugin as it will fail

Fix ts configuration reoslving

---

package.json
pnpm-lock.yaml
src/build-config.ts
test/integration.test.ts
test/integration/esm-shims/package.json
test/integration/esm-shims/src/index.js

Resolve #275. 
Inject esm shims by `@rollup/plugin-esm-shim`. 
The  `@rollup/plugin-esm-shim` is enabled by default, not sure if we should disable it by default and enable it via a `shims` option like `tsup` and `unbuild`

feat: esm shims

---

.github/workflows/ci.yml
README.md

This PR added usage and a few examples for the `bin` field support.
Resolves #291

docs: add bin docs to readme

---

package.json
pnpm-lock.yaml

Resolves #273
`rollup-swc-preserve-directives` is fully removed from lock file

Update swc3 plugin

---

.github/workflows/ci.yml
package.json

As rollup requires to work with node 18, even node 16 CI is passing but still not recommended to use with node 16

Change required node version to lgt 18

---

.github/workflows/ci.yml
package.json
src/build-config.ts
src/plugins/prepend-directives.ts
src/plugins/raw-plugin.ts
test/compile.test.ts
test/post-build/compile.test.ts
test/post-build/integration.test.ts

* Simplify post-build test
* Remove console
* Polish raw plugin

refactor: simplify redudant calls, polish code

---

src/build-config.ts
test/integration.test.ts
test/integration/server-components/package.json
test/unit/use-client/__snapshot__/use-client.js.snapshot
test/unit/use-client/__snapshot__/use-client.min.js.snapshot

Add hash to make sure the chunks are unique, when there're both esm and cjs builds the chunks will still be bound to the syntax correctly

Generate hash for chunk

---

src/build-config.ts

`hoistTransitiveImports` behavior of rollup could break RSC due to the imports are hoisted into entry chunk acrossing the server/client boundaries. Disable it to avoid the client imports showing up in entry chunk
Fixes #315

Disable hoistTransitiveImports

---

src/build-config.ts
src/bundle.ts
test/integration.test.ts

Declaration type files are not correctly generated for react-server, edge, react-native condition.
This also simplify the collect entries calls into only one.

Fix missing dts for special exports

---

src/build-config.ts
src/bundle.ts
src/logger.ts
src/plugins/size-plugin.ts

keep the logging state in the same context of the build, and save more info into context

Refactor logging plugin

---

src/build-config.ts
src/bundle.ts
src/plugins/size-plugin.ts
test/integration.test.ts
test/integration/server-components-split/package.json
test/integration/server-components-split/src/_client.js
test/integration/server-components-split/src/index.js
test/integration/server-components-split/src/ui.js
test/integration/server-components/src/_asset.js

Resolves #327 
In split chunks phase, collect the sub modules of the entry, if they're having layer, and the same layer with the entry, push them to the `dependencyGraphMap`.
And then we go through to check the current module. If the module is imported by the entry:
* when the module layer is same as entry layer, keep it as part of entry and don't split it;
* when the module layer is different from entry layer, split the module into a separate chunk as a separate boundary.

perf: improve code split strategy for RSC

---

src/exports.ts
test/unit/exports.test.ts

Should support nested export condition (`import` or `require` etc), then the value has both types and default, should get  the path from nested condition
```
exports: {
'.': {
'import': {
'types': './dist/index.d.ts',
'default': './dist/index.mjs'
},
'require': {
'types': './dist/index.d.ts',
'default': './dist/index.js'
}
}
}
```

Fix parsing nested exports case

---

src/build-config.ts
src/typescript.ts
test/integration.test.ts
test/integration/ts-no-emit/package.json
test/integration/ts-no-emit/src/index.ts
test/integration/ts-no-emit/tsconfig.json

Fixes #339 
Avoid users having bad option in `tsconfig.json` that breaks types generation

Override compiler options for dts

---

src/build-config.ts
src/exports.ts
src/utils.ts
test/unit/exports.test.ts

Skip `types` condition to avoid collecting non-js entry
Fixes #341

Fix export types condition

---

src/exports.ts
test/unit/exports.test.ts

Need to handle both string and object value of an export condition.
`import: {} | import: ""`
Fixes #352

Fix: mixed exports

---

README.md
src/constants.ts

re-export Type `SWRConfiguration` bumps to this warning. We don't need to warn it from bundler
```
"SWRConfiguration" is imported from external module "swr/_internal" but never used in "src/core/serialize.ts", "src/core/use-swr.ts" and "src/core/index.ts".
```

Skip unused import warning

---

pnpm-lock.yaml
src/build-config.ts
src/bundle.ts
src/plugins/alias-plugin.ts
src/plugins/size-plugin.ts
src/typescript.ts
test/integration.test.ts
test/integration/pkg-exports-ts-rsc/package.json
test/integration/pkg-exports-ts-rsc/src/api/index.ts
test/integration/pkg-exports-ts-rsc/tsconfig.json

When users provide the special entry (react-server, react-native), avoid the package name being alias to `<pkg.react-server>`

Filter special export type out from alias

---

src/build-config.ts
src/bundle.ts
src/plugins/output-state-plugin.ts

* Group more global build context together like cwd, pkg, export paths..
* Simplify arguments

refactor: group build context

---

src/bin/index.ts
src/build-config.ts
src/bundle.ts
src/constants.ts
src/exports.ts
src/lib/wildcard.ts
src/logger.ts
src/prepare.ts
src/utils.ts
test/integration.test.ts

* Optional configure `types` field
* By default, output `"type": "module"` and esm/cjs exports with correct extension. `require` condition with `.cjs` files

Fix ts resolving of prepare

---

src/lib/wildcard.ts
src/utils.ts
test/integration/no-entry/package.json

If the dir and source file is not existed, it might error
For example searching `style.css/index.js`

Fix retrieving bad source file from src folder

---

src/prepare.ts
test/integration.test.ts

This PR ensures to log "Detected using TypeScript but tsconfig.json is missing, created a tsconfig.json for you." only if the tsconfig does not exist.

fix: do not log "Detected using TS but tsconfig is missing" if tsconfig exists

---

src/bundle.ts

In watch mode, bunchee log output look like: 
```bash
❯ bunchee -w    
Exports  File  Size
Watching assets in /Users/nnecec/Github/bunchee...
```
I think don't need log output state in watch mode.

fix: no log output state in watch mode

---

src/build-config.ts
test/integration.test.ts
test/integration/ts-incremental-with-buildinfofile/package.json
test/integration/ts-incremental-with-buildinfofile/src/index.ts
test/integration/ts-incremental-with-buildinfofile/tsconfig.json
test/testing-utils.ts

Fixes #386 
can't disable the incremental config for dts generation as it still can work and disabling might breaks ts rules

Fix ts incremental error when tsbuildfile is specified

---

src/prepare.ts
test/integration.test.ts

When run prepare
* Still override main/module
* Only update existing `exports` field

enahnce: improve esm module prepare

---

README.md
src/build-config.ts
src/bundle.ts
src/constants.ts
src/plugins/output-state-plugin.ts
src/types.ts
src/utils.ts
test/integration.test.ts
test/integration/dev-prod-convention/package.json
test/integration/dev-prod-convention/src/index.development.js
test/integration/dev-prod-convention/src/index.production.js

Resolves #391 
A feature that already has in webpack, and proposed by @amannn 
If you have `"development": "./dist/index.development.js"`, `NODE_ENV: development` will be injected by default;
If you have `"production": "./dist/index.production.js"`, `NODE_ENV: production` will be injected by default;

feat: auto inject env for development and production condition

---

src/build-config.ts
test/integration.test.ts

Fixes #406 
Ideally would pull all the ts compiler option values from `tsconfig.json` as override config for dts plugin. or let dts plugin not use the partial compiler options as override options. Then there's no `{ incremental: true }` or `{ composite: true, incremental: false }` case that being resolved
Or avoid dts plugin avoid resolving the tsconfig.json to read options, so we can always use the simple overriden ones

Fix ts-composite project build failure

---

src/plugins/output-state-plugin.ts
test/integration.test.ts
test/integration/output-short/package.json
test/integration/output-short/src/index.js

resolve https://github.com/huozhi/bunchee/issues/404 (✌️I fixed the 404 issue)
Because of `console.log` will auto add a space between two args, I cancel combine `arg + space` like `prefix` before.

fix: Logging is off format

---

src/lint.ts
test/integration.test.ts
test/integration/cjs-pkg-esm-main-field/package.json
test/integration/cjs-pkg-esm-main-field/src/index.js
test/integration/esm-pkg-cjs-main-field/package.json
test/integration/esm-pkg-cjs-main-field/src/index.cjs

Fixes #420 
There was a case that`main` field was not built in #268, then we introduced a rule that `main` cannot be `index.cjs` which is wrong. But it should be valid now

Fix: bad lint rule for main field

---

src/build-config.ts
src/bundle.ts
src/plugins/alias-plugin.ts
src/types.ts
src/utils.ts
test/integration.test.ts
test/integration/multi-entries/package.json
test/integration/pkg-exports-ts-rsc/package.json
test/integration/pkg-exports-ts-rsc/src/api/index.ts
test/integration/pkg-exports-ts-rsc/src/index.ts

This PR refactors each build to a standalone rollup build job including its own `input` and own `output`, instead of having one `input` and multi `output` before.
For `.d.cts` and `.d.mts` we need to import the proper file, for instance, `.d.cts` matches `.cjs` files and `.d.mts` matches `.mjs` files, so you would have:
In a `.d.mts` file, module resolving situation will be like
```ts
// index.d.mts
export { Shared } from '../shared/index.mjs'; // ✅
export { Shared } from '../shared/index'; // ❌ cannot resolve
export { Shared } from '../shared/index.cjs'; // ❌ cannot resolve
```
This means we need a resolving map for each format of build, if we're building import condition output with esm syntax format, we need to alias the code to mjs output. This rule only applies to types. JS can still …

Generate relative path for types

---

src/build-config.ts
test/integration.test.ts
test/integration/edge-variable/package.json
test/integration/edge-variable/src/index.js

Resolves #410 
Replace `EdgeRuntime` global variable to `"edge-runtime"` string in `.edge-light` build

Replace EdgeRuntime for edge build

---

src/bin/index.ts
src/bundle.ts
test/cli.test.ts

I sometimes wonder if I've built done in watch mode, because it print nothing when built sucessfully.
 
Do we need to print some hint like these in watch mode?
```bash
> bunchee -w
Watching project /Users/nnecec/Github/bunchee...
📦 Build in: 1.956s
📦 Build in: 595.334ms
src/bundle.ts(25,3): error TS6133: 'getPackageMeta' is declared but its value is never read.
src/bundle.ts(70,64): error TS2304: Cannot find name 'pkg'.
src/bundle.ts(71,38): error TS2304: Cannot find name 'pkg'.
src/bundle.ts(73,38): error TS2304: Cannot find name 'pkg'.
src/bundle.ts(75,26): error TS2304: Cannot find name 'pkg'.
src/bundle.ts(153,40): error TS2304: Cannot find name 'pkg'.
src/bundle.ts(177,5): error TS18004: No value exists in scope for the shorthand property 'pkg'. Either declare one or provide an …
```

feat: print end status in watch mode

---

src/bundle.ts

If you configure `"exports": "./index"`, bunchee shouldn't delete `./` dir automatically after build

enhance: dont delete dir if it is cwd

---

src/build-config.ts
test/integration.test.ts
test/integration/ts-import-json/package.json
test/integration/ts-import-json/src/index.ts
test/integration/ts-import-json/tsconfig.json

When user import json module in ts module, types generation breaks. Cause we need to let ts generation also be able to resolve json file

Fix ts pkg import json

---

package.json
pnpm-lock.yaml
src/build-config.ts
src/plugins/esm-shim.ts
test/integration.test.ts
test/integration/esm-shims/package.json
test/integration/esm-shims/src/dirname.js
test/integration/esm-shims/src/filename.js
test/integration/esm-shims/src/index.js
test/integration/esm-shims/src/require.js

Drop the `@rollup/plugin-esm-shim` plugin and rewrite one with AST parsing, due to it causes issues by the regex matching and replacing with shims. It cannot optionally inject the shims based on the usage.
The new plugin is using the AST parsing, and based on the cjs API you're using we inject the certain ones of polyfill and replace the usage. If you only use one, we won't insert two polyfills.
It can handle all the import paths, `@rollup/plugin-esm-shim` will break with `@scope` module path, but AST parsing won't have that problem
Resolves #442

Rewrite esm-shim plugin

---

src/bundle.ts

if we print `console.log(startTime, watcherCount)` in `end` function, it looks like:
```bash
❯ bunchee -w
Watching project /Users/nnecec/Github/bunchee...
523.054045021534 1
523.054045021534 2
523.054045021534 3
523.054045021534 4
✓ Build in 3250.67ms
523.054045021534 5
523.054045021534 6
523.054045021534 7
523.054045021534 8
523.054045021534 9
523.054045021534 10
```
`logWatcherBuildTime` will be executed only once at the beginning. So we need reset `startTime` and `watcherCount` in the `start` function.
Also, if we modify a file, it may not trigger a rebuild of all the entry files, so the `watcherCount` maybe not equal to `result.length`.

fix: algorithm for determine the end of build in watch mode

---

src/build-config.ts
test/integration.test.ts
test/testing-utils.ts

`d.ts` should resolve cjs files when the package.json "type" is cjs type

fix: cjs .d.ts types resolving

---

test/integration/basic-jsx/index.test.ts
test/integration/bin/cts/fixtures/.gitignore
test/integration/bin/cts/index.test.ts
test/integration/bin/multi-path/fixtures/.gitignore
test/integration/bin/multi-path/index.test.ts
test/integration/bin/single-path/fixtures/.gitignore
test/integration/bin/single-path/index.test.ts
test/integration/cjs-pkg-esm-main-field/index.test.ts
test/integration/default-node-mjs/index.test.ts
test/integration/dev-prod-convention/fixtures/.gitignore
test/integration/dev-prod-convention/index.test.ts
test/integration/duplicate-entry/index.test.ts
test/integration/edge-variable/index.test.ts
test/integration/entry-index-index/index.test.ts
test/integration/esm-pkg-cjs-main-field/index.test.ts
test/integration/esm-shims/index.test.ts
test/integration/externals/index.test.ts
test/integration/invalid-exports-cjs/index.test.ts
test/integration/invalid-exports-esm/index.test.ts
test/integration/js-only/index.test.ts

As stated in https://github.com/huozhi/bunchee/pull/455#discussion_r1493786108 and https://github.com/huozhi/bunchee/pull/455#discussion_r1493786266, this PR modifies the migrated integration tests for later works.
Extends PR #455
Extends Issue #449

refactor: modify migrated integration test format to be a guide for the upcoming works

---

src/plugins/output-state-plugin.ts
test/integration.test.ts

The binaries are not display above the exports now, it's fine that doesn't not block bundling. Tweak the tests to make it work and will investigate later

Fix output format

---

README.md

Executing with npm results in 
```shell
npm bunchee --prepare
Unknown command: "bunchee"
To see a list of supported npm commands, run:
npm help
```

Fix bunchee command execution in readme

---

src/build-config.ts

If a project is one of a monorepo, navigate to the project and run it maybe print the `Circular dependency` warnings.
```bash
Circular dependency: ../../node_modules/.pnpm/culori@4.0.1/node_modules/culori/src/parse.js -> ../../node_modules/.pnpm/culori@4.0.1/node_modules/culori/src/modes.js -> ../../node_modules/.pnpm/culori@4.0.1/node_modules/culori/src/converter.js -> ../../node_modules/.pnpm/culori@4.0.1/node_modules/culori/src/_prepare.js -> ../../node_modules/.pnpm/culori@4.0.1/node_modules/culori/src/parse.js
```
Update the `Circular dependency` regex expression.

fix: regex expression of circular dependency

---

src/bundle.ts
src/lint.ts
test/integration/subpath-imports/index.test.ts
test/integration/subpath-imports/package.json
test/integration/subpath-imports/src/index.js
test/integration/subpath-imports/src/lib/polyfill.js

* add test for subpath imports
* refactor a bit the lint code to avoid duplicated warning

subpath imports

---

src/bin/index.ts
src/bundle.ts
src/types.ts
src/typescript.ts
test/integration.test.ts
test/integration/tsconfig-override/index.test.ts
test/integration/tsconfig-override/package.json
test/integration/tsconfig-override/src/index.ts
test/integration/tsconfig-override/tsconfig.build.json
test/integration/tsconfig-override/tsconfig.json

Allows using a custom path for tsconfig during build. Useful if you for example have one tsconfig for editor experience and a different one for build
(ref https://github.com/pingdotgg/uploadthing/tree/main/packages/uploadthing - base tsconfig has path overrides to resolve source code types during dev, but we don't want the built output to use those paths)

feat: allow overrding tsconfig path

---

package.json
pnpm-lock.yaml
test/cli/output-in-watch/index.test.ts
test/integration.test.ts
test/testing-utils.ts

The PR replaces `tsx` with `@swc-node/register`.
`bunchee` already prefers swc, it doesn't make sense to use esbuild as the build script loader.  Let's switch it to swc.

chore: replace `tsx` with swc

---

src/build-config.ts
src/utils.ts

This PR will ensure we only create dts plugin once, seems the plugin consumed too much memory. And we also ensure the override ts parsing is also only executed once so we don't read the tsconfig.json and parse multi times in each type build
Resolves #491 
Closes #493

fix: memory overflow issue

---

src/build-config.ts
src/lib/memoize.ts
src/typescript.ts
src/utils.ts
test/unit/memoize.test.ts
tsconfig.json

Fixes cache mismatching caused in #493 
The cache was re-created very time, now we give memoizeByKey a scoped cache that it won't recreate.

fix memoize util causing cache mismatch

---

.github/workflows/ci.yml
src/entries.ts

`dirent.path` is `deprecated` and also not supported in node 16
https://github.com/emilkowalski/vaul/actions/runs/8509833761/job/23306167226?pr=315

fix: avoid using dirent.path and add node 16

---

src/typescript.ts

This closes #530.
The newly added logic works in both Node and Bun. The old logic only works in Node.

Added support for Bun

---

src/build-config.ts
src/bundle.ts
src/rollup-job.ts
src/types.ts
test/integration/unspecified-types-paths/index.test.ts
test/integration/unspecified-types-paths/package.json
test/integration/unspecified-types-paths/src/subpath/nested.ts

When there's no types specified in exports, bunchee should not generate a type file
Reported by @dferber90

Fix: types generation for missing types case

---

package.json
src/build-config.ts
src/bundle.ts
src/plugins/alias-plugin.ts
src/types.ts
test/integration/multi-entries/package.json
test/integration/multi-exports-ts/index.test.ts
test/integration/pkg-exports-ts-rsc/index.test.ts
test/integration/shared-entry/index.test.ts

This will PR generates the relative paths relationship for the JS bundles. 
For instance, for the 2 exports which one is relying on the other one, and `./foo` is dependent on `./`, project name is "my-lib":
```
- src/
|- index.ts
|- foo.ts
```
Bunchee will output the below structure and use `"<project name>/<export path>"` as dependency for each bundle to import the other export bundles. e.g. foo.js will import from `"my-lib"` as it's the `./` export.
```
- dist/
|- index.js
|- foo.js
```
This output is not ideal cause it might resolve the 2nd module resolving. And some bundler might error (e.g. vite).
After this PR, the output the relative path for all imports and there's no extra module resolving. And we did some smart resolution which also based on the output format, to make sure CJS …

feat: generate relative imports

---

src/entries.ts
test/integration/dev-prod-special-convention/index.test.ts
test/integration/dev-prod-special-convention/package.json
test/integration/dev-prod-special-convention/src/index.react-server.ts
test/integration/dev-prod-special-convention/src/index.ts

When the existing default condition will generate the output, don't override the condition
Fixes #541

fix: special shouldnt override default condition

---

src/build-config.ts
src/entries.ts
src/plugins/alias-plugin.ts
test/integration/dev-prod-convention-reexport/index.test.ts
test/integration/dev-prod-convention-reexport/package.json
test/integration/dev-prod-convention-reexport/src/core.ts
test/integration/dev-prod-convention-reexport/src/index.ts

`development` condition is declared first, then it's always get picked
We should pass down the current condition names of entry to alias plugin, to let it decide which condition shall we alias.
- If there's special condition matched in other exports, prefer those ones;
- If there's no special condition matched, fallback to default if there's no other conditon (import/require) based on bundle type (cjs or esm);
Fixes #548

Fix conditional export bundle mapping

---

src/bin/index.ts
src/entries.ts
test/integration/entry-index-index/index.test.ts
test/integration/entry-index-index/package.json

* If it's index/index, build should still work
* logging was omitted in build by spinner

fix: index-index nested output and logging

---

src/plugins/esm-shim.ts
test/integration/esm-shims/index.test.ts
test/integration/esm-shims/package.json
test/integration/esm-shims/src/custom-require.js

If it's customized require calls, it should need the global nodejs polyfill for esm-shim
Fixes #564

fix: require detection of esm-shims plugin

---

src/build-config.ts
test/integration/shared-module-ts/index.test.ts
test/integration/shared-module-ts/package.json
test/integration/shared-module-ts/src/another.ts
test/integration/shared-module-ts/src/index.react-server.ts
test/integration/shared-module-ts/src/index.ts
test/integration/shared-module-ts/src/lib/app-context.shared-runtime.ts
test/integration/shared-module-ts/src/lib/util.shared-runtime.ts

When it's running dts job, change the extension of `chunkFileNames` to `d.ts`
Fixes #547

Fix shared chunk type file extension

---

src/build-config.ts
test/compile/use-client/__snapshot__/use-client.js.snapshot
test/compile/use-client/__snapshot__/use-client.min.js.snapshot
test/integration/shared-module-ts-esm/index.test.ts
test/integration/shared-module-ts-esm/package.json
test/integration/shared-module-ts-esm/src/index.ts
test/integration/shared-module-ts-esm/src/lib/util.shared-runtime.ts
test/integration/shared-module-ts/package.json

When output shared chunk file: 
- if it's ESM package and CJS chunk, use `.cjs` extension
- if it's CJS package and ESM chunk, use `.mjs` extension
- otherwise just use '.js' extension
Fixes #557

Fix shared chunk extension along with parent chunk

---

src/bin/index.ts
src/build-config.ts
src/types.ts
test/cli/dts-bundle/base.ts
test/cli/dts-bundle/index.test.ts

Fix #560 
Added a CLI flag `--dts-bundle` that will enable `rollup-plugin-dts`'s `respectExternal` option.

feat(dts): support bundle dts

---

src/lint.ts
src/plugins/output-state-plugin.ts
src/utils.ts
test/integration/js-bad-configured-types/index.test.ts
test/integration/js-bad-configured-types/package.json
test/integration/js-bad-configured-types/src/index.js

feat: error on bad type export

---

src/constants.ts
test/integration/ts-exports-multiple-conditions/index.test.ts
test/integration/ts-exports-multiple-conditions/package.json
test/integration/ts-exports-multiple-conditions/src/index.browser.ts
test/integration/ts-exports-multiple-conditions/src/index.edge-light.ts
test/integration/ts-exports-multiple-conditions/src/index.ts
test/integration/ts-exports-multiple-conditions/src/index.workerd.ts

Support more popular common runtime like `workerd`, `bun`, `deno` and `browser`

fix: support more special fields of target runtime

---

test/integration/js-only/index.test.ts

Note: worthy to improve the error when there's tsconfiguration but only js entries detected

test: add test for js with tsconfig error

---

README.md
src/bundle.ts
src/rollup/input.ts
src/types.ts
test/integration/browserslist/index.test.ts
test/integration/browserslist/package.json
test/integration/browserslist/src/index.js

Closes #587 
Support `browserslist` in package.json.
This doesn't support the rc file cause we don't need to extend the dependency

Support browserlists from package.json

---

package.json
pnpm-lock.yaml
src/entries.ts
src/prepare/index.ts
src/prepare/prepare-entries.ts
src/utils.ts
test/cli/dts-bundle/package.json

Migrate manual traverse to `glob`, prepare for the later special convention detection

refactor: use glob to do file matching

---

README.md
src/bin/index.ts
test/integration/prepare-js/index.test.ts
test/integration/prepare-ts-with-pkg-json/index.test.ts
test/integration/prepare-ts-with-test-file/index.test.ts
test/integration/prepare-ts/index.test.ts

Since `prepare()` is not building the project itself, more like setup the project. It should be more flexible that could receive more options if possible in the future, thus we separate it to a different command.

Change prepare option to command

---

src/plugins/esm-shim.test.ts
src/plugins/esm-shim.ts

enhance: improve the esm-shim matching

---

src/plugins/prepend-directives.ts

Fix the error when build with `--sourcemap`
```
[plugin prependDirective] Sourcemap is likely to be incorrect: a plugin (prependDirective) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

fix: prepend plugin sourcemap

---

src/bin/index.ts

Warn users to use the new command `bunchee prepare`

Warn on --prepare is deprecated

---

src/rollup/input.ts
test/compile/treeshake/__snapshot__/treeshake.js.snapshot
test/compile/treeshake/__snapshot__/treeshake.min.js.snapshot
test/compile/treeshake/input.js

The treeshake option is not merged with default preset, it's using the explicit configured option unless you speicify a preset. 
We know enable the tree-shaking with "recommended" preset
According to the doc: `"recommended" should work well for most usage patterns. Some semantic issues may be swallowed, though (treeshake.unknownGlobalSideEffects: false, treeshake.correctVarValueBeforeDeclaration: false)`

fix: enable rollup default tree-shaking

---

src/constants.ts
src/entries.ts
src/prepare/prepare-entries.ts
test/integration/shared-any-module/index.test.ts
test/integration/shared-any-module/package.json
test/integration/shared-any-module/src/_internal/util-a.js
test/integration/shared-any-module/src/_internal/util-b.js
test/integration/shared-any-module/src/export-a.js
test/integration/shared-any-module/src/export-b.js
test/integration/shared-any-module/src/export-c.js
test/integration/shared-any-module/src/private/_nested/util-c.js

If I have a lot of internal files that wanted to be share across multiple entries, e.g. `_internal/**` and each entry randomly imports the internal files, we could create some shared chunks for `_internal/**` so that each shared module will have a new chunk.
For example
```
- src
| - _internal/
|- util-a
|- util-b
| - entry-a
| - entry-b
```
In the dependency graph, `entry-a` imports `util-a`, and `entry-b` imports `util-b`. we could just create 2 chunks for `_internal/util-a` and `_internal/util-b` instead of asking users to use a barrel file like `_internal/index.ts` or rename everything under `_internal` with a underscore prefix.
Closes #617

feat: support mark any underscore module as private

---

src/entries.ts
src/exports.ts
src/util/file-path.test.ts
src/util/file-path.ts
src/utils.ts
test/integration/conflicted-entry/conflicted-entry.test.ts
test/integration/conflicted-entry/package.json
test/integration/conflicted-entry/src/foo.ts
test/integration/conflicted-entry/src/foo/index.jsx
test/tsconfig.json

If there's duplicated entry like `foo/index.js` and `foo.js` we can error in build `Conflicted entry files found for entries: ./foo'`
Closes #593

feat: error on duplicated entries

---

src/entries.ts
test/integration/shared-module-with-suffix/package.json
test/integration/shared-module-with-suffix/shared-module-with-suffix.test.ts
test/integration/shared-module-with-suffix/src/_private/util.browser.ts
test/integration/shared-module-with-suffix/src/client/index.ts

The shared module might alias to the import.types or require.types condition instead of js bundle

fix: js bundle alias of shared module

---

README.md
src/env.ts
test/integration/dev-prod-convention/index.test.ts

Replacing `NODE_ENV` by default could result into unexpected behavior when the environment change and it's not easy to opt-out. Remove the default env here to provide easier defaults for users to bundle and still possible to opt-in with set `NODE_ENV`

remove the default behavior of env replacement on node env

---

package.json
src/rollup/input.ts
test/integration/dynamic-require/dynamic-require.test.ts
test/integration/dynamic-require/node_modules/external-lib/index.js
test/integration/dynamic-require/node_modules/external-lib/package.json
test/integration/dynamic-require/package.json
test/integration/dynamic-require/src/foo.js
test/integration/dynamic-require/src/index.js
test/integration/dynamic-require/src/required-module.js
test/integration/esm-shims/index.test.ts
test/integration/unspecified-types-paths/index.test.ts
test/integration/utils.ts
test/testing-utils.ts
test/tsconfig.json
tsconfig.json

Turn on the commonjs plugin transform flag to handle `require()` in the source code. Include the module when needed and this will avoid the esm-shim issue 
Resolves #626 
Fixes #468

feat: handle dynamic require in ESM

---

package.json
pnpm-lock.yaml
src/entries.ts
src/prepare/prepare-entries.ts
test/integration/prepare-js/index.test.ts
test/integration/prepare-ts/index.test.ts
test/testing-utils/index.ts

enhance: replace glob with fast-glob

---

.prettierignore
src/bin/index.ts
src/bundle.ts
src/lib/normalize-error.ts
src/rollup-job.ts
src/types.ts
test/integration/errors/compile-error/package.json
test/integration/errors/compile-error/src/index.tsx

* Ensure errors are thrown
* Ensure normalizing the rollup plugin errors
Closes #641

enhance: improve error logging

---

.github/workflows/ci.yml

* add node setup job
* add node v22 test matrix

ci: should setup node.js

---

src/plugins/alias-plugin.ts
test/integration/exports-order/index.test.ts
test/integration/exports-order/package.json
test/integration/exports-order/src/a.ts
test/integration/exports-order/src/index.ts
test/integration/exports-order/src/utils.ts

Fixes: https://github.com/huozhi/bunchee/issues/652, https://github.com/run-llama/LlamaIndexTS/issues/1623

fix: prefer to use the same exports name if possible

---

src/prepare/index.ts

Currently, `bunchee prepare` writes to the `package.json` file without an EOL, this usually causes issues. The PR makes `bunchee prepare` to include EOL.
All tests passed locally.

fix: `prepare` append EOL to `package.json`

---

src/bundle.ts
test/integration/missing-entry-file/missing-entry-file.test.ts
test/integration/missing-entry-file/package.json
test/integration/missing-entry-file/src/index.js

Show a warning for the entries that defined but missing the source files
Example, if you're missing defining entries for `./foo` and `./bar`, you'll see the warning
```
! The following exports are defined in package.json but missing source files:
⨯ ./foo
⨯ ./bar
```
Closes #673

[dx] warn on missing entries

---

src/rollup-job.ts

bunchee removes all files before recreating them, which causes a lot of temporary errors about missing files. This could potentially break hmr during the build of a large monorepo. Since the types files can be missing in the middle of the process

disable removing output in watch mode

---

src/rollup/output.ts
src/utils.ts

When package name contains `-` it will throw the error from rollup when output with `iife` or `umd`
```
Error [RollupError]: Given name "bunchee-test" is not a legal JS identifier. If you need this, you can try "output.extend: true".
code: 'ILLEGAL_IDENTIFIER_AS_NAME',
url: 'https://rollupjs.org/configuration-options/#output-extend'
```
Setting extend to `true` to avoid it
```
Whether to extend the global variable defined by the name option in umd or iife formats. When true, the global variable will be defined as (global.name = global.name || {}). When false, the global defined by name will be overwritten like (global.name = {}).
```

fix: iife invalid name rollup error

---

package.json
pnpm-lock.yaml
src/bin/index.ts

Replace `ora` with `nanospinner`:
- 20 times smaller than `ora`
- tiny with only single dependency
- dual CJS/ESM package (no dynamic import required)
- fulfill bunchee's requirements
---
All tests passed locally.
Here is a demo of the final output (you can verify that with `pnpm run build`)

refactor: replace `ora` with `nanospinner`
