README.md, bin/cli.js, src/bundle.js, src/rollup-config.js
=> enhance: output option

package.json, src/rollup-config.ts, yarn.lock
related to https://github.com/rollup/plugins/issues/287
=> fix: specify ts plugin to 3.1.1

src/rollup-config.ts
=> enhance: disable buble on ts

src/bundle.ts, src/cli.ts, src/rollup-config.ts, src/types.ts, test/cli.test.js, test/fixtures/shebang.js
* add `--shebang` argument for compiling cli binary
* unit test for shebang cli
=> feat: support shebang

package.json, src/cli.ts, test/compile.test.js, yarn.lock
* separate deps between cli and index
* self host
=> feature: self host

package.json, src/rollup-config.ts, test/__snapshots__/compile.test.js.snap, test/unit/es-basic/input.js, yarn.lock
=> feat: support class properties

.gitignore, package.json, src/bundle.ts, src/cli.ts, src/index.ts, src/rollup-config.ts, src/utils.ts, test/__snapshots__/compile.test.js.snap, test/unit/es-advance/input.js, tsconfig.json, yarn.lock
* replace internal babel config with babel-preset-o
* self-host with ts-node instead of using last version
=> feature: adopt babel-preset-o

README.md, src/bundle.ts, src/cli.ts, src/rollup-config.ts, src/types.ts, test/cli.test.js
* Add `--no-sourcemap` to disable sourcemap gen
=> cli: --no-soucemap

README.md, src/rollup-config.ts, test/__snapshots__/compile.test.js.snap, test/compile.test.js, test/unit/jsx/input.jsx, test/unit/tsx/input.tsx, test/unit/tsx/tsconfig.json
=> fix: resolve jsx file ext

package.json, src/bundle.ts, src/cli.ts, src/pkg.ts, src/rollup-config.ts, yarn.lock
fix `cwd` option doesn't work well in CLI
=> fix: cli cwd option

package.json, src/rollup-config.ts, test/__snapshots__/compile.test.js.snap, test/unit/es-basic/input.js, yarn.lock
=> feature: transform all by default

package.json, src/bundle.ts, src/cli.ts, src/index.ts, src/rollup-config.ts, src/utils.ts, test/compile.test.js, yarn.lock
* remove esmodule interop in cli.ts
* use export to be compatible with ccommonjs
=> enhance: remove interop on cli

README.md, package.json, src/cli.ts, src/rollup-config.ts, src/types.ts, src/utils.ts
=> enhance: support target node

README.md, package.json
=> mark ts as optional dep

package.json, src/bundle.ts, src/cli.ts, src/rollup-config.ts, src/utils.ts, test/cli.test.js, test/compile.test.js, test/integration.test.js, test/integration/ts-error/.gitignore, test/integration/ts-error/index.ts, test/integration/ts-error/node_modules/typescript/index.js, yarn.lock
* Change dep `typescript` to peerDep and devDep
* add test when ts is not loaded
=> enhance: make typescript as optional dep

package.json, test/__snapshots__/compile.test.js.snap, test/unit/es-basic/input.js, test/unit/module/a.js, test/unit/ts-basic/input.ts, yarn.lock
=> Fix regenerator polyfill

README.md, src/rollup-config.ts, test/integration.test.js, test/integration/pkg-exports-default/index.js, test/integration/pkg-exports-default/package.json
* support `node` and `default` conditions
* update docs
=> enhance: exports sugar and update doc

src/cli.ts, src/rollup-config.ts, src/types.ts, src/utils.ts, test/cli.test.js, test/fixtures/with-externals.js
=> feat: support manual externals

env.d.ts, package.json, src/bundle.ts, src/cli.ts, src/config.ts, src/index.ts, src/rollup-config.ts, src/types.ts, src/utils.ts, test/integration.test.js, yarn.lock
* format code into a more comfortable styling
* bump dev dep ts to 4.8.2
=> Format code and bump ts

src/bundle.ts
=> Fix watch mode for multiple entries

README.md
=> docs: update readme for advanced usage

src/rollup-config.ts, test/cli.test.js, test/fixtures/es2020.js, test/fixtures/es2020.ts
=> Fix typescript transform target

src/rollup-config.ts, test/cli.test.js, test/compile.test.js
Should respect cli arg format if compile from cli
=> Fix cli format

package.json, src/rollup-config.ts, yarn.lock
* swc plugin could resolve compiler options from tsconfig itself and apply proper react transform options. https://github.com/huozhi/bunchee/pull/118#discussion_r961419875
* also this bump remove the unused deps https://github.com/SukkaW/rollup-plugin-swc/pull/20
=> feat: leverage swc3 plugin tsconfig resolving

README.md, cli.ts, package.json, src/bundle.ts, src/rollup-config.ts, src/utils.ts, test/tsconfig.json, tsconfig.json, yarn.lock
* Separate tsconfig for testing, since `baseUrl` and `paths` will break typescript resolving with `module` for building process
* Upgrade tsx
* Fix umd missing `output.name`
* Polish help message and readme
=> Improve format support and fix tsconfig for testing

cli.ts, src/bundle.ts, src/utils.ts
* Log duration for each build
* Avoid duplicated logs
=> Add duration to logs and fix duplicated logs

src/rollup-config.ts
Should generate the types based on input file when there's input file from CLI
=> Fix types generation

README.md
=> Update node API docs in readme

package.json, yarn.lock
=> Bump rollup related packages

src/rollup-config.ts
=> fix esmodule mark detection

src/rollup-config.ts, test/unit/ts-interop/tsconfig.base.json, test/unit/ts-interop/tsconfig.json
=> Parse fully resolved tsconfig

src/rollup-config.ts, test/cli.test.ts, test/unit/ts-target-es2018/__snapshot__/ts-target-es2018.js.snapshot, test/unit/ts-target-es2018/__snapshot__/ts-target-es2018.min.js.snapshot, test/unit/ts-target-es2018/input.ts, test/unit/ts-target-es2018/tsconfig.json
=> feat: leverage ts config target as output target

.gitignore, cli.ts, src/bundle.ts, src/rollup-config.ts, test/cli.test.ts, test/fixtures/single-entry/package.json, test/fixtures/single-entry/src/index.js, test/integration/single-entry/package.json
=> Fix custom entry path is broken (#172)

cli.ts, package.json, test/integration.test.ts, test/integration/publint/index.js, test/integration/publint/package.json, yarn.lock
* After build, will use `publint` to check the package.json and bundle assets
* Add logging for watching mode
=> feat: integrate publint for package.json after build

cli.ts, package.json, src/bundle.ts, src/rollup-config.ts, src/types.ts, test/cli.test.ts, test/fixtures/with-externals.js, yarn.lock
Support multiple external dependencies:
```
bunchee --external:react-dom,react
```
You can also bundle everything
```
bunchee --no-external
```
=> feat: support both external and no-external

src/bundle.ts, test/cli.test.ts, test/integration.test.ts
Fixes #188 
Always try to generate typescript if there's typescript specified
=> Fix type generation for single entry

src/plugins/directive-plugin.ts, test/unit/use-client/__snapshot__/use-client.js.snapshot, test/unit/use-client/__snapshot__/use-client.min.js.snapshot, test/unit/use-client/client.js, test/unit/use-client/input.js
Fixes the follow up issue from #217
=> merge directives for output

test/compile.test.ts, test/testing-utils.ts, test/unit/jsx-preserve/__snapshot__/jsx-preserve.d.ts.snapshot, test/unit/jsx-preserve/__snapshot__/jsx-preserve.min.d.ts.snapshot, test/unit/jsx-react-automatic/__snapshot__/jsx-react-automatic.d.ts.snapshot, test/unit/jsx-react-automatic/__snapshot__/jsx-react-automatic.min.d.ts.snapshot, test/unit/ts-basic/__snapshot__/ts-basic.d.ts.snapshot, test/unit/ts-basic/__snapshot__/ts-basic.min.d.ts.snapshot, test/unit/ts-interop/__snapshot__/ts-interop.d.ts.snapshot, test/unit/ts-interop/__snapshot__/ts-interop.min.d.ts.snapshot, test/unit/ts-target-es2018/__snapshot__/ts-target-es2018.d.ts.snapshot, test/unit/ts-target-es2018/__snapshot__/ts-target-es2018.min.d.ts.snapshot, test/unit/tsx/__snapshot__/tsx.d.ts.snapshot, test/unit/tsx/__snapshot__/tsx.min.d.ts.snapshot
=> chore: add types test case into snapshot

src/bundle.ts, src/cli.ts, test/cli.test.ts, test/fixtures/no-entry/package.json, test/fixtures/no-entry/src/no-entry.txt, test/integration.test.ts, test/integration/no-entry/package.json, test/integration/no-entry/src/no-entry.txt
=> Improve warning if no entry file in src

src/build-config.ts, test/unit/ts-target-es2018/__snapshot__/ts-target-es2018.js.snapshot, test/unit/ts-target-es2018/input.ts
=> fix: remove directives from type file

package.json, pnpm-lock.yaml, src/build-config.ts, src/types.ts, src/typescript.ts, test/unit/jsx-react-automatic/tsconfig.json
Passing down the resolved options for dts plugin
=> Improve ts compilation options for dts plugin

package.json, pnpm-lock.yaml, test/unit/es-advance/__snapshot__/es-advance.min.js.snapshot, test/unit/module/__snapshot__/module.min.js.snapshot
There was some minifier improvements, so test snapshots should be updated
=> build: Update `@swc/core`

package.json, pnpm-lock.yaml, src/build-config.ts
It's a package rename change
x-ref: https://github.com/huozhi/rollup-preserve-directives/releases/tag/v1.0.0
=> Replace rollup-swc-preserve-directives with rollup-preserve-directives

package.json, src/bin/bunchee.ts, src/bin/index.ts, test/cli.test.ts, test/integration.test.ts
Based on the changes @devjiwonchoi and me landed in #272 , now we can self hoist bunchee that to let it to build itself.
The "bin" field cli and the core API can be built separately at the same time
=> build: self hoist

src/build-config.ts, src/plugins/raw-plugin.ts, test/integration.test.ts, test/integration/raw-data/package.json, test/integration/raw-data/src/content.txt, test/integration/raw-data/src/index.js
=> Support raw data imports

package.json, pnpm-lock.yaml
Fixes #297 
kudos to @SukkaW fixing this issue on the plugin side 
x-ref: https://github.com/huozhi/rollup-preserve-directives/pull/17
=> Upgrade directive plugin

src/build-config.ts, src/exports.ts, test/cli.test.ts, test/integration.test.ts
refactor esm pkg detection and removed outdated warnings
=> refactor esm pkg detection

README.md
=> docs: add readme for data content

src/build-config.ts
Create a step that generates the entries map first, key is the source file and the value is a config containing the export condition
=> refactor to collect entries

src/build-config.ts
Resolves #326 
x-ref: https://rollupjs.org/migration/
=> Filter annotation warning

src/build-config.ts
=> Change fallback jsx transform to automatic react-jsx for tsconfig

src/plugins/size-plugin.ts, test/integration.test.ts, test/testing-utils.ts
=> log full chunk path

package.json, pnpm-lock.yaml, src/bin/index.ts, src/logger.ts, src/plugins/size-plugin.ts, test/integration.test.ts
=> Improve logging

src/plugins/inline-css.ts, test/fixtures/compile/tsx-css-global/__snapshot__/tsx-css-global.js.snapshot, test/fixtures/compile/tsx-css-global/__snapshot__/tsx-css-global.min.js.snapshot
Fix import css helper is missing
=> Fix css import helper

src/constants.ts, src/plugins/prepend-directives.ts
=> fix: bad sourcemap from prepend directive

src/plugins/size-plugin.ts, test/integration.test.ts, test/testing-utils.ts
Resolves #346 dedupe logs
Resolves #309 testing improvement
=> filter duplicated logs and simplify testing utils

src/build-config.ts
Found during upgrade applying bunchee to vaul
=> optional preserveSymlinks

test/integration.test.ts, test/integration/entry-index-index/package.json, test/integration/entry-index-index/src/index/index.js, test/integration/entry-index-index/src/index/index.react-server.js
=> test: add tests for index-index

src/build-config.ts, src/bundle.ts, src/logger.ts, src/plugins/output-state-plugin.ts, test/integration.test.ts, test/integration/output/package.json, test/integration/output/src/bin/cli.js, test/integration/output/src/foo.js, test/integration/output/src/index.js, test/integration/output/src/index.react-server.js
Prettier output as more clear format
=> prettier the log format

src/constants.ts, src/prepare.ts, src/utils.ts, test/integration.test.ts, test/integration/prepare-ts/.gitignore
Follow up for #103 
* auto config `main`, `module`, `types` field if possible
* create `tsconfig.json` if it's using ts but not having `tsconfig.json`
=> prepare node10 main resolution and tsconfig

src/bundle.ts
Resolve https://github.com/huozhi/bunchee/issues/372.
Catch and log error at watch mode.
=> fix: don't exits process at watch mode when error

src/bundle.ts, src/typescript.ts, src/utils.ts
=> enahnce: improve error message

src/plugins/output-state-plugin.ts, test/integration/output/package.json
=> Fix logging of scoped package

src/prepare.ts, test/integration.test.ts, test/integration/prepare-ts-with-pkg-json/.gitignore, test/integration/prepare-ts-with-pkg-json/src/index.ts
=> Fix prepare command with existing pkg json

src/build-config.ts, src/constants.ts, src/prepare.ts, src/utils.ts, test/integration.test.ts, test/integration/multi-entries/src/client.ts, test/integration/multi-entries/src/server/index.ts, test/integration/multi-entries/src/shared.ts, test/integration/multi-entries/tsconfig.json
Also add test for checking if types are shared
=> perf: change array to set

src/build-config.ts, src/bundle.ts, src/exports.ts, src/plugins/output-state-plugin.ts, src/types.ts, src/utils.ts, test/unit/exports.test.ts
Simplify types generation, prepare for the entry paths alias simplication
=> Refactor types generation

README.md
=> docs: complete clean api

src/build-config.ts, test/integration.test.ts, test/integration/basic-jsx/package.json, test/integration/basic-jsx/src/index.js
Testing against respinner, found this bug
=> Fix plugin orders for basic jsx

src/prepare.ts
=> Fix only prepare existing exports

src/bin/index.ts, src/bundle.ts, test/cli.test.ts
=> Do not clean when entry file is from cli

src/exports.ts, test/integration.test.ts, test/integration/esm-pkg-cjs-main-field/package.json, test/integration/esm-pkg-cjs-main-field/src/index.js
=> Fix esm package with cjs entry

src/build-config.ts
=> Fix: set preserveSymlinks to false for types generation

src/build-config.ts, test/integration.test.ts, test/integration/server-components/package.json
=> fix: generate cjs extension chunk when the entry is cjs

test/cli/basic/index.test.ts, test/cli/cjs-relative-imports/index.test.ts, test/cli/dts/index.test.ts, test/cli/env-var/index.test.ts, test/cli/externals/index.test.ts, test/cli/no-entry/index.test.ts, test/cli/output-in-watch/index.test.ts, test/cli/single-entry-js/index.test.ts, test/cli/target/index.test.ts, test/cli/utils.ts, test/cli/workspace/index.test.ts, test/testing-utils.ts
* Auto clean up the distDir
* use callback style to run tests
=> test: refactor cli test suite

package.json, pnpm-lock.yaml, test/compile/use-client/__snapshot__/use-client.js.snapshot, test/compile/use-client/__snapshot__/use-client.min.js.snapshot
=> chore: upgrade rollup to latest

src/build-config.ts, test/compile/ts-target-es2018/__snapshot__/ts-target-es2018.min.js.snapshot, test/compile/use-client/__snapshot__/use-client.min.js.snapshot
=> Fix: preserving directives in minification

src/plugins/output-state-plugin.ts
=> fix: dedupe output files

README.md, src/build-config.ts, test/integration/shared-module/index.test.ts, test/integration/shared-module/package.json, test/integration/shared-module/src/index.js, test/integration/shared-module/src/index.react-server.js, test/integration/shared-module/src/lib/app-context.shared-runtime.js
Follow up for #429 
* Change the split chunks with names and layer, different shared module should be split into different groups
* Add docs with examples
=> feat: shared modules and docs

README.md
missed adding the option in the readme
=> docs: update docs from #489

src/plugins/output-state-plugin.ts
=> hide non entry chunks

src/constants.ts, src/plugins/alias-plugin.ts, test/integration/multi-exports-ts/index.test.ts, test/integration/multi-exports-ts/package.json, test/integration/multi-exports-ts/src/types.ts
=> Fix default types generation

src/exports.ts, test/integration/invalid-exports-cjs/index.test.ts, test/integration/invalid-exports-cjs/package.json
=> fix: lint rule for module field

examples/custom-jsx/package.json, examples/custom-jsx/src/index.tsx, examples/custom-jsx/tsconfig.json
=> examples: add vue for custom jsx example

package.json, pnpm-lock.yaml, src/bin/index.ts
=> Revert "feat: loading indicator (#523)"

src/bin/index.ts, test/cli/output-in-watch/index.test.ts
=> Fix watch mode spinner

src/bin/index.ts, test/cli/output-in-watch/index.test.ts
Fix dev spinner didn't show up during editing files in watch mode
=> fix: dev spinner

src/entries.ts, src/plugins/alias-plugin.ts, test/integration/pkg-exports-ts-rsc/index.test.ts, test/integration/pkg-exports-ts-rsc/package.json, test/integration/pkg-exports-ts-rsc/src/api/index.react-server.ts
Fixes #546 
For special condition relying on other entries, should still do alias, fallback to using default condition alias
=> Fix special cond alias

package.json, pnpm-lock.yaml
I'm trying to add running tests of `bunchee` to the SWC deploy pipeline so it never breaks unexpectedly. Minifier improvements may break tests, but it's _expected_.
See: https://github.com/swc-project/swc/pull/9068
=> chore: Update `@swc/core`

src/utils.ts
=> fix: skip remove src dir

test/integration/multi-entries/index.test.ts
The multi-entry test was missing in #475
=> test: add missing test

package.json, pnpm-lock.yaml
Fix CVE issue https://github.com/rollup/rollup/pull/5671
=> chore: bump rollup version

src/entries.ts, src/prepare/prepare-entries.ts, src/utils.ts, test/integration/shared-module/index.test.ts, test/integration/shared-module/src/_internal/index.js, test/integration/shared-module/src/_internal/index.react-server.js, test/integration/shared-module/src/index.react-server.js
Handle the dependency of `_<name>.<runtime>.<ext>` private internal modules
=> feat: handle special cond import for shared module

src/plugins/esm-shim.test.ts, src/plugins/esm-shim.ts
x-ref: https://github.com/huozhi/bunchee/pull/601#issuecomment-2496140091
=> fix: resolve variable

README.md
=> fixed grammatical error

src/rollup/input.ts, src/rollup/output.ts, test/fixtures/integration-test-template/index.test.ts, test/integration/sourcemap-dts/index.test.ts, test/integration/sourcemap-dts/package.json, test/integration/sourcemap-dts/src/index.ts, test/testing-utils/index.ts
=> fix: do not emit sourcemap for types

package.json, pnpm-lock.yaml, src/bundle.ts, src/rollup/input.ts, src/rollup/split-chunks.ts, src/typescript.ts, test/compile/use-client/__snapshot__/use-client.js.snapshot, test/compile/use-client/__snapshot__/use-client.min.js.snapshot, test/integration/mixed-directives/mixed-directives.test.ts, test/integration/server-components/index.test.ts
Replace the `-client-` or `-server-` from chunk file into hash `-<hash>-`.
=> enhance: simplfy chunk type

src/plugins/raw-plugin.ts
* read file async
* normalize file content for windows
=> enhance: handle raw query on windows, async read file
